# String slicing and other functions in python
mystr = "luffy is a Good boy"
print(mystr)
print(len(mystr))
print(mystr[0:5])
print(mystr[0:19])
print(mystr[0:])
print(mystr[:5])
print(mystr[:])
print(mystr[0:5:2])
print(mystr[::])
print(mystr[-3:])
print(mystr[-1::])
#to reverse a line
print(mystr[::-1])
print(mystr[::-2])
print(mystr.isalnum())
print(mystr.isalpha())
print(mystr.endswith("boy"))
print(mystr.endswith("bto"))
print(mystr.count("o"))
print(mystr.capitalize())
print(mystr.lower())
print(mystr.upper())
print(mystr.find("is"))
print(mystr.replace("is","is not"))
